/** @format */

import Head from "next/head";
import Image from "next/image";
import About from "../components/About/About";
import Banner from "../components/Banner/Banner";

import Contact from "../components/Contact/Contact";
import Footer from "../components/Footer/Footer";
import Menu from "../components/Menu/Menu";
import NavBar from "../components/NavBar/NavBar";
import Subscribe from "../components/Subscribe/Subscribe";
import styles from "../styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { useDisclosure } from "@chakra-ui/react";
import CartDrawer from "../components/Cart/CartDrawer";

export default function Home() {
   const { onClose, onOpen, isOpen } = useDisclosure();

   return (
      <div className={styles.container}>
         <Head>
            <title>Cake Fairy</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/fairy1.png" />
         </Head>
         <NavBar onOpen={onOpen} />
         <Banner />
         <Menu />
         <Subscribe />
         <About />
         <Contact />
         <Footer />
         <CartDrawer isOpen={isOpen} onClose={onClose} />
      </div>
   );
}
