import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About/About'
import Banner from '../components/Banner/Banner'
import Contact from '../components/Contact/Contact'
import Footer from '../components/Footer/Footer'
import Menu from '../components/Menu/Menu'
import NavBar from '../components/NavBar/NavBar'
import styles from '../styles/Home.module.css'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar/>
      <Banner/>
      {/* <Menu /> */}
      <About />
      <Contact />
      <Footer />
    </div>
  )
}
